name: CD Sync to S3

on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      shell: bash
      run: |
        cargo build --release
    
    - name: Arrange
      shell: bash
      run: |
        mkdir deploy_dir
        cp ./target/release/axum_prototype ./deploy_dir/executable.run
        strip ./deploy_dir/executable.run
        cp ./Dockerfile ./deploy_dir/

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Sync to S3
      run: aws s3 sync ./deploy_dir/ s3://${{ secrets.AWS_BUCKET }} 
